version: '3.8'
services:     
  
  promocodefactory-webhost-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    image: ${DOCKER_USERNAME}/promocodefactory-webhost-api:latest
    container_name: 'promocodefactory-webhost-api'
    restart: on-failure
    ports:
      - "7050:8080"
      - "5292:8081"  # порт для отладки
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - POSTGRES_CONNECTION_STRING=Server=postgres_db;Port=5432;Database=postgres_db;User Id=postgres;Password=password;
    networks:
      - myLocalNetwork   
      
networks:
  myLocalNetwork:
    external: true