name: ASP.NET Core CI/CD

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './src'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Clean NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore --disable-parallel
        working-directory: ${{env.working-directory}}
        env:
          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{env.working-directory}}

      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish
        working-directory: ${{env.working-directory}}/Otus.Teaching.PromoCodeFactory.WebHost

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
         context: ./src
         file: ./src/Otus.Teaching.PromoCodeFactory.WebHost/Dockerfile
         push: true
         tags: |
          ${{ secrets.DOCKER_USERNAME }}/promocodefactory-webhost-api:latest
          ${{ secrets.DOCKER_USERNAME }}/promocodefactory-webhost-api:${{ github.ref_name }}

      - name: Logout from Docker Hub
        run: docker logout